// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFleetManAPI.Infrastructure.Model;

public partial class TblCitymaster
{
    public int CityId { get; set; }

    public string CityName { get; set; }

    public int? IsMainBranch { get; set; }

    public bool? IsServingCity { get; set; }

    public int? Active { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }
}