// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using MyFleetManAPI.DataAccess.Models;

namespace MyFleetManAPI.DataAccess.Data;

public partial class MyFleetManDbContext : DbContext
{
    public MyFleetManDbContext(DbContextOptions<MyFleetManDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TblEmployee> TblEmployees { get; set; }

    public virtual DbSet<TblErrorlog> TblErrorlogs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TblEmployee>(entity =>
        {
            entity.HasKey(e => e.EmployeeId).HasName("pk_tbl_employee");

            entity.ToTable("tbl_employee");

            entity.Property(e => e.EmployeeId).HasColumnName("employee_id");
            entity.Property(e => e.Active).HasColumnName("active");
            entity.Property(e => e.Address)
                .HasMaxLength(350)
                .HasColumnName("address");
            entity.Property(e => e.Address2)
                .HasMaxLength(350)
                .HasColumnName("address_2");
            entity.Property(e => e.Address3)
                .HasMaxLength(350)
                .HasColumnName("address_3");
            entity.Property(e => e.AddressDocPath)
                .IsUnicode(false)
                .HasColumnName("address_doc_path");
            entity.Property(e => e.AddressProofId).HasColumnName("address_proof_id");
            entity.Property(e => e.AddressProofNo)
                .IsUnicode(false)
                .HasColumnName("address_proof_no");
            entity.Property(e => e.AdharCardDocPath)
                .HasMaxLength(250)
                .HasColumnName("adhar_card_doc_path");
            entity.Property(e => e.AdharCardNo)
                .HasMaxLength(50)
                .HasColumnName("adhar_card_no");
            entity.Property(e => e.AspnetUserId).HasColumnName("aspnet_user_id");
            entity.Property(e => e.BackgroundVerificationDocPath)
                .HasMaxLength(250)
                .HasColumnName("background_verification_doc_path");
            entity.Property(e => e.BackgroundVerificationExpDate)
                .HasColumnType("datetime")
                .HasColumnName("background_verification_exp_date");
            entity.Property(e => e.BranchId).HasColumnName("branch_id");
            entity.Property(e => e.BranchWithOutletId).HasColumnName("branch_with_outlet_id");
            entity.Property(e => e.ChangePasswordDate)
                .HasColumnType("datetime")
                .HasColumnName("change_password_date");
            entity.Property(e => e.CityServingCode).HasColumnName("city_serving_code");
            entity.Property(e => e.CompanyClientId).HasColumnName("company_client_id");
            entity.Property(e => e.CountryPhoneCode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("country_phone_code");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasColumnType("datetime")
                .HasColumnName("created_on");
            entity.Property(e => e.DateOfJoining)
                .HasColumnType("datetime")
                .HasColumnName("date_of_joining");
            entity.Property(e => e.DeptId).HasColumnName("dept_id");
            entity.Property(e => e.DigitalSignature)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("digital_signature");
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .HasColumnName("email");
            entity.Property(e => e.EmployeeCode)
                .HasMaxLength(350)
                .HasColumnName("employee_code");
            entity.Property(e => e.FirstName)
                .HasMaxLength(350)
                .HasColumnName("first_name");
            entity.Property(e => e.Gender)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("gender");
            entity.Property(e => e.IdDocPath)
                .IsUnicode(false)
                .HasColumnName("id_doc_path");
            entity.Property(e => e.IdProofId).HasColumnName("id_proof_id");
            entity.Property(e => e.IdProofNo)
                .IsUnicode(false)
                .HasColumnName("id_proof_no");
            entity.Property(e => e.InstallationId).HasColumnName("installation_id");
            entity.Property(e => e.IsAllowGuestBooking).HasColumnName("is_allow_guest_booking");
            entity.Property(e => e.IsBackgroundVerification).HasColumnName("is_background_verification");
            entity.Property(e => e.IsCorporateUser).HasColumnName("is_corporate_user");
            entity.Property(e => e.IsCorporateUserApprove).HasColumnName("is_corporate_user_approve");
            entity.Property(e => e.IsFirstLogin).HasColumnName("is_first_login");
            entity.Property(e => e.IsLoginIpValidate).HasColumnName("is_login_ip_validate");
            entity.Property(e => e.IsMobileNoVerify).HasColumnName("is_mobile_no_verify");
            entity.Property(e => e.IsPoliceVerification).HasColumnName("is_police_verification");
            entity.Property(e => e.IsVerified).HasColumnName("is_verified");
            entity.Property(e => e.IsWhitelist).HasColumnName("is_whitelist");
            entity.Property(e => e.LastLoginDateTime)
                .HasColumnType("datetime")
                .HasColumnName("last_login_date_time");
            entity.Property(e => e.LastName)
                .HasMaxLength(350)
                .HasColumnName("last_name");
            entity.Property(e => e.LevelId).HasColumnName("level_id");
            entity.Property(e => e.LoginIpAddress).HasColumnName("login_ip_address");
            entity.Property(e => e.ManagerId).HasColumnName("manager_id");
            entity.Property(e => e.MiddleName)
                .HasMaxLength(350)
                .HasColumnName("middle_name");
            entity.Property(e => e.Mobile)
                .HasMaxLength(50)
                .HasColumnName("mobile");
            entity.Property(e => e.ModifiedBy).HasColumnName("modified_by");
            entity.Property(e => e.ModifiedOn)
                .HasColumnType("datetime")
                .HasColumnName("modified_on");
            entity.Property(e => e.PanCardDocPath)
                .HasMaxLength(250)
                .HasColumnName("pan_card_doc_path");
            entity.Property(e => e.PanCardNo)
                .HasMaxLength(50)
                .HasColumnName("pan_card_no");
            entity.Property(e => e.PfNo)
                .HasMaxLength(50)
                .HasColumnName("pf_no");
            entity.Property(e => e.PinCode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("pin_code");
            entity.Property(e => e.PoliceVerificationDocPath)
                .HasMaxLength(250)
                .HasColumnName("police_verification_doc_path");
            entity.Property(e => e.PoliceVerificationExpDate)
                .HasColumnType("datetime")
                .HasColumnName("police_verification_exp_date");
            entity.Property(e => e.RegistrationMobileNo)
                .HasMaxLength(50)
                .HasColumnName("registration_mobile_no");
            entity.Property(e => e.Remark)
                .IsUnicode(false)
                .HasColumnName("remark");
            entity.Property(e => e.RoleId)
                .HasMaxLength(100)
                .HasColumnName("role_id");
            entity.Property(e => e.TdsApplicable).HasColumnName("tds_applicable");
            entity.Property(e => e.TdsName)
                .HasMaxLength(50)
                .HasColumnName("tds_name");
            entity.Property(e => e.TdsPercentage)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("tds_percentage");
            entity.Property(e => e.UanNo)
                .HasMaxLength(50)
                .HasColumnName("uan_no");
        });

        modelBuilder.Entity<TblErrorlog>(entity =>
        {
            entity.HasKey(e => e.ErrorId).HasFillFactor(90);

            entity.ToTable("tbl_errorlogs");

            entity.Property(e => e.ErrorId).HasColumnName("error_id");
            entity.Property(e => e.Action)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("action");
            entity.Property(e => e.Controller)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("controller");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_on");
            entity.Property(e => e.ErrorMessage)
                .IsUnicode(false)
                .HasColumnName("error_message");
            entity.Property(e => e.Method)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("method");
            entity.Property(e => e.Path)
                .IsUnicode(false)
                .HasColumnName("path");
            entity.Property(e => e.StackTrace)
                .IsUnicode(false)
                .HasColumnName("stack_trace");
            entity.Property(e => e.StpName)
                .IsUnicode(false)
                .HasColumnName("stp_name");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}