// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using MyFleetManAPI.Infrastructure.Model;

namespace MyFleetManAPI.Infrastructure.Identity;

public partial class MyFleetManIdentityDbContext : IdentityDbContext<AspNetUser, IdentityRole<Guid>, Guid>
{
    public MyFleetManIdentityDbContext(DbContextOptions<MyFleetManIdentityDbContext> options)
        : base(options)
    {
    }
    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);
    }
}