// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFleetManAPI.DataAccess.Models;

public partial class TblErrorlog
{
    public long ErrorId { get; set; }

    public string Controller { get; set; }

    public string Action { get; set; }

    public string Path { get; set; }

    public string Method { get; set; }

    public string ErrorMessage { get; set; }

    public string StackTrace { get; set; }

    public string StpName { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }
}