
CREATE TABLE [dbo].[tbl_employee](
	[employee_id] [int] IDENTITY(1,1) NOT NULL,
	[employee_code] [nvarchar](350) NULL,
	[first_name] [nvarchar](350) NULL,
	[middle_name] [nvarchar](350) NULL,
	[last_name] [nvarchar](350) NULL,
	[city_serving_code] [int] NULL,
	[address] [nvarchar](350) NULL,
	[address_2] [nvarchar](350) NULL,
	[address_3] [nvarchar](350) NULL,
	[pin_code] [varchar](50) NULL,
	[gender] [char](1) NULL,
	[branch_id] [int] NULL,
	[mobile] [nvarchar](50) NULL,
	[email] [nvarchar](50) NULL,
	[aspnet_user_id] [uniqueidentifier] NULL,
	[is_first_login] [int] NULL,
	[last_login_date_time] [datetime] NULL,
	[role_id] [nvarchar](100) NULL,
	[company_client_id] [int] NULL,
	[digital_signature] [varchar](500) NULL,
	[date_of_joining] [datetime] NULL,
	[id_proof_id] [int] NULL,
	[id_proof_no] [varchar](max) NULL,
	[id_doc_path] [varchar](max) NULL,
	[address_proof_id] [int] NULL,
	[address_proof_no] [varchar](max) NULL,
	[address_doc_path] [varchar](max) NULL,
	[tds_applicable] [bit] NULL,
	[tds_percentage] [decimal](18, 2) NULL,
	[tds_name] [nvarchar](50) NULL,
	[installation_id] [bigint] NULL,
	[branch_with_outlet_id] [bigint] NULL,
	[login_ip_address] [nvarchar](max) NULL,
	[is_login_ip_validate] [bit] NULL,
	[pf_no] [nvarchar](50) NULL,
	[pan_card_no] [nvarchar](50) NULL,
	[pan_card_doc_path] [nvarchar](250) NULL,
	[adhar_card_no] [nvarchar](50) NULL,
	[adhar_card_doc_path] [nvarchar](250) NULL,
	[uan_no] [nvarchar](50) NULL,
	[is_background_verification] [bit] NULL,
	[background_verification_doc_path] [nvarchar](250) NULL,
	[background_verification_exp_date] [datetime] NULL,
	[is_police_verification] [bit] NULL,
	[police_verification_doc_path] [nvarchar](250) NULL,
	[police_verification_exp_date] [datetime] NULL,
	[country_phone_code] [varchar](50) NULL,
	[change_password_date] [datetime] NULL,
	[registration_mobile_no] [nvarchar](50) NULL,
	[is_mobile_no_verify] [bit] NULL,
	[is_whitelist] [bit] NULL,
	[dept_id] [int] NULL,
	[manager_id] [int] NULL,
	[is_corporate_user] [int] NULL,
	[is_corporate_user_approve] [int] NULL,
	[is_verified] [bit] NULL,
	[remark] [varchar](max) NULL,
	[level_id] [int] NULL,
	[is_allow_guest_booking] [bit] NULL,
	[active] [int] NULL,
	[created_by] [int] NULL,
	[created_on] [datetime] NULL,
	[modified_by] [int] NULL,
	[modified_on] [datetime] NULL,
 CONSTRAINT [pk_tbl_employee] PRIMARY KEY CLUSTERED 
(
	[employee_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO